import dukeHash

print(dukeHash.hash("Hello World"))
print(dukeHash.hash("Hello World!"))
print(dukeHash.hash("Hello World!areiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiöjsssssssssssssssssssssssssaoiewrrrrrrrrrrrrrrrrrrrrrrrrrrrrzfgoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewaoiewazgbssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"))